[project]
name = "foragers-world-rl"
version = "0.1.0"
description = "A JAX grid-world where foragers eat, breed and evolve, controlled by an RL agent"
readme = "README.md"
authors = [
    { name = "raymogg", email = "raymondmogg@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "jax>=0.6.2",
]

[project.scripts]
foragers-world-rl = "foragers_world_rl:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
